apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myserver
  strategy: {}
  template:
    metadata:
      labels:
        app: myserver
    spec:
      containers:
      - image: espirado/saramiscore
        name: myserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path:  /
            port:  8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        livenessProbe:
          httpGet:
            path:  /upload
            port:  8000
        readinessProbe:
          httpGet:
            path: /upload
            port: 8000    
