apiVersion: v1
kind: Service
metadata:
  name: myserver
  namespace: {{ .Values.namespace }}
  labels:
    app: myserver
spec:
  selector:
    app: myserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: {{ .Values.service.port }}
